FROM nvcr.io/nvidia/pytorch:22.09-py3
LABEL maintainer="Brad Larson"

#USER root
ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN --mount=type=cache,target=/var/cache/apt \ 
    apt-get update -y && apt-get install -y --no-install-recommends \
    wget && \
    rm -rf /var/lib/apt/lists/*

#RUN useradd -D user
#USER user
#WORKDIR /home/user

COPY requirements-job.txt .
RUN --mount=type=cache,target=/var/cache/apt \
    pip3 install -r requirements-job.txt

RUN echo 'alias py=python3' >> ~/.bashrc

WORKDIR /app
ENV LANG C.UTF-8
ENV PYTHONUNBUFFERED=1

# port 3000: debugger
# port 6006: tensorboard
EXPOSE 3000 6006 
# PYTHONUNBUFFERED=1 smooths the logfile updates in Kubernetes

#ARG CACHEBUST 
COPY test test
COPY config config
COPY creds.yaml creds.yaml

# Launch training
CMD ["python3","-u", "test/parallelddp.py"]