name: sm
description: System modeling playground
dockerbuild:
- name: job
  dockerfile: dockerfile-job
  context: .
- name: dev
  dockerfile: dockerfile
  context: .
  build_arg:
  - key: IMAGE
    value: job
version:
  major: 0
  minor: 0
  patch: 38
  label: ''
gpus: all
registry: localhost:32000
image_names:
- name: job
  image_name: localhost:32000/job:0.0.38
- name: dev
  image_name: localhost:32000/dev:0.0.38
